### PR TITLE
Variable fonts

### PR DESCRIPTION
**Pull request by m4rc1e**
@davelab6 These variable fonts are created from the modifications made in #5, merge this first.

I had to alter the sources a little in order for fontmake to generate the vfs. I've added a readme to replicate the necessary steps.

### CODE REVIEW

**Comment by m4rc1e** [comment]
avar matches static instances

screen shot 2018-06-18 at 11 43 55

Font menus lgtm

screen shot 2018-06-18 at 11 44 46

**Comment by davelab6** [comment]
@m4rc1e oof this has now merge conflicts

**Comment by m4rc1e** [comment]
Rebased it sir

**Comment by davelab6** [comment]
Cheers

**Pull request merged**
